package geoip

import (
	"net"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"testing"
	"time"

	maxminddb "github.com/oschwald/maxminddb-golang"
)

// minimalMMDB is a valid but empty MaxMind DB (IPv4, 1 node, 24-bit record size).
// No IPs map to any data record, so all lookups return empty results.
// Generated by hand-encoding the MMDB binary format:
//   - 1 node (6 bytes): left=1, right=1 (both point to node_count, meaning "no record")
//   - 16-byte data separator
//   - empty data section
//   - metadata marker + metadata map
var minimalMMDB = []byte{
	// Node 0 (24-bit record size = 6 bytes per node): left=1, right=1
	0x00, 0x00, 0x01, 0x00, 0x00, 0x01,
	// 16-byte data section separator
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	// Metadata marker: \xAB\xCD\xEFMaxMind.com
	0xAB, 0xCD, 0xEF, 0x4D, 0x61, 0x78, 0x4D, 0x69,
	0x6E, 0x64, 0x2E, 0x63, 0x6F, 0x6D,
	// Metadata map (7 keys, type=map encoded as 0xE7)
	0xE7,
	// "binary_format_major_version" -> uint32(2)
	0x5B, 0x62, 0x69, 0x6E, 0x61, 0x72, 0x79, 0x5F,
	0x66, 0x6F, 0x72, 0x6D, 0x61, 0x74, 0x5F, 0x6D,
	0x61, 0x6A, 0x6F, 0x72, 0x5F, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6F, 0x6E, 0xC1, 0x02,
	// "binary_format_minor_version" -> uint32(0)
	0x5B, 0x62, 0x69, 0x6E, 0x61, 0x72, 0x79, 0x5F,
	0x66, 0x6F, 0x72, 0x6D, 0x61, 0x74, 0x5F, 0x6D,
	0x69, 0x6E, 0x6F, 0x72, 0x5F, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6F, 0x6E, 0xC1, 0x00,
	// "build_epoch" -> uint32(0)
	0x4B, 0x62, 0x75, 0x69, 0x6C, 0x64, 0x5F, 0x65,
	0x70, 0x6F, 0x63, 0x68, 0xC1, 0x00,
	// "database_type" -> string("test")
	0x4D, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73,
	0x65, 0x5F, 0x74, 0x79, 0x70, 0x65, 0x44, 0x74,
	0x65, 0x73, 0x74,
	// "ip_version" -> uint32(4)
	0x4A, 0x69, 0x70, 0x5F, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6F, 0x6E, 0xC1, 0x04,
	// "node_count" -> uint32(1)
	0x4A, 0x6E, 0x6F, 0x64, 0x65, 0x5F, 0x63, 0x6F,
	0x75, 0x6E, 0x74, 0xC1, 0x01,
	// "record_size" -> uint32(24)
	0x4B, 0x72, 0x65, 0x63, 0x6F, 0x72, 0x64, 0x5F,
	0x73, 0x69, 0x7A, 0x65, 0xC1, 0x18,
}

// mustMMDBReader opens minimalMMDB via FromBytes and panics on error.
// Used in tests that need a non-nil *maxminddb.Reader without real data.
func mustMMDBReader(t *testing.T) *maxminddb.Reader {
	t.Helper()
	r, err := maxminddb.FromBytes(minimalMMDB)
	if err != nil {
		t.Fatalf("failed to open minimal MMDB: %v", err)
	}
	return r
}

// allFiles returns all four database file paths for a manager.
func allFiles(m *GeoIPManager) []string {
	return []string{m.asnFile, m.countryFile, m.cityV4File, m.cityV6File}
}

// --- NewGeoIPManager ---

func TestNewGeoIPManager_PathConstruction(t *testing.T) {
	m := NewGeoIPManager("/data")
	want := filepath.Join("/data", "security", "geoip")
	if m.dataDir != want {
		t.Errorf("dataDir = %q, want %q", m.dataDir, want)
	}
	if m.asnFile != filepath.Join(want, "asn.mmdb") {
		t.Errorf("asnFile = %q", m.asnFile)
	}
	if m.countryFile != filepath.Join(want, "country.mmdb") {
		t.Errorf("countryFile = %q", m.countryFile)
	}
	if m.cityV4File != filepath.Join(want, "dbip-city-ipv4.mmdb") {
		t.Errorf("cityV4File = %q", m.cityV4File)
	}
	if m.cityV6File != filepath.Join(want, "dbip-city-ipv6.mmdb") {
		t.Errorf("cityV6File = %q", m.cityV6File)
	}
	if m.updateInterval != updateInterval {
		t.Errorf("updateInterval = %v, want %v", m.updateInterval, updateInterval)
	}
}

func TestNewGeoIPManager_EmptyDataDir(t *testing.T) {
	m := NewGeoIPManager("")
	if m == nil {
		t.Fatal("expected non-nil manager")
	}
	if m.dataDir == "" {
		t.Error("dataDir should not be empty even for empty input")
	}
}

// --- databasesExist ---

func TestDatabasesExist_AllMissing(t *testing.T) {
	m := NewGeoIPManager(t.TempDir())
	if m.databasesExist() {
		t.Error("expected false when no database files exist")
	}
}

func TestDatabasesExist_PartiallyPresent(t *testing.T) {
	dir := t.TempDir()
	m := NewGeoIPManager(dir)
	geoDir := filepath.Join(dir, "security", "geoip")
	if err := os.MkdirAll(geoDir, 0755); err != nil {
		t.Fatal(err)
	}
	// Create only the asn file — the rest are absent
	if err := os.WriteFile(m.asnFile, []byte{}, 0644); err != nil {
		t.Fatal(err)
	}
	if m.databasesExist() {
		t.Error("expected false when only some database files exist")
	}
}

func TestDatabasesExist_AllPresent(t *testing.T) {
	dir := t.TempDir()
	m := NewGeoIPManager(dir)
	geoDir := filepath.Join(dir, "security", "geoip")
	if err := os.MkdirAll(geoDir, 0755); err != nil {
		t.Fatal(err)
	}
	for _, f := range allFiles(m) {
		if err := os.WriteFile(f, []byte{}, 0644); err != nil {
			t.Fatal(err)
		}
	}
	if !m.databasesExist() {
		t.Error("expected true when all database files exist")
	}
}

// --- ShouldUpdate / LastUpdate ---

func TestShouldUpdate_NeverUpdated(t *testing.T) {
	m := NewGeoIPManager(t.TempDir())
	// lastUpdate is zero value — should report that update is needed
	if !m.ShouldUpdate() {
		t.Error("expected ShouldUpdate() == true for fresh manager")
	}
}

func TestShouldUpdate_JustUpdated(t *testing.T) {
	m := NewGeoIPManager(t.TempDir())
	m.lastUpdate = time.Now()
	if m.ShouldUpdate() {
		t.Error("expected ShouldUpdate() == false immediately after update")
	}
}

func TestShouldUpdate_UpdateIntervalExceeded(t *testing.T) {
	m := NewGeoIPManager(t.TempDir())
	// Simulate a lastUpdate older than the interval
	m.lastUpdate = time.Now().Add(-(updateInterval + time.Second))
	if !m.ShouldUpdate() {
		t.Error("expected ShouldUpdate() == true when interval exceeded")
	}
}

func TestLastUpdate_ReturnsLastUpdate(t *testing.T) {
	m := NewGeoIPManager(t.TempDir())
	before := time.Now()
	m.lastUpdate = before
	got := m.LastUpdate()
	if !got.Equal(before) {
		t.Errorf("LastUpdate() = %v, want %v", got, before)
	}
}

func TestLastUpdate_ZeroByDefault(t *testing.T) {
	m := NewGeoIPManager(t.TempDir())
	if !m.LastUpdate().IsZero() {
		t.Error("expected zero LastUpdate for fresh manager")
	}
}

// --- GetStatus ---

func TestGetStatus_NilDBs(t *testing.T) {
	m := NewGeoIPManager(t.TempDir())
	s := m.GetStatus()
	if !s.Enabled {
		t.Error("Enabled should always be true")
	}
	if s.ASNEnabled {
		t.Error("ASNEnabled should be false when asnDB is nil")
	}
	if s.CountryEnabled {
		t.Error("CountryEnabled should be false when countryDB is nil")
	}
	if s.CityEnabled {
		t.Error("CityEnabled should be false when cityDB is nil")
	}
	if s.DatabasesExist {
		t.Error("DatabasesExist should be false for an empty dir")
	}
	if !s.LastUpdate.IsZero() {
		t.Error("LastUpdate should be zero for fresh manager")
	}
}

func TestGetStatus_WithDBs(t *testing.T) {
	m := NewGeoIPManager(t.TempDir())
	m.cityV4DB = mustMMDBReader(t)
	m.countryDB = mustMMDBReader(t)
	m.asnDB = mustMMDBReader(t)

	s := m.GetStatus()
	if !s.Enabled {
		t.Error("Enabled should be true")
	}
	if !s.ASNEnabled {
		t.Error("ASNEnabled should be true when asnDB is set")
	}
	if !s.CountryEnabled {
		t.Error("CountryEnabled should be true when countryDB is set")
	}
	if !s.CityEnabled {
		t.Error("CityEnabled should be true when cityDB is set")
	}
}

// --- Reader ---

func TestReader_ReturnsNonNil(t *testing.T) {
	m := NewGeoIPManager(t.TempDir())
	r := m.Reader()
	if r == nil {
		t.Fatal("Reader() returned nil")
	}
}

func TestReader_IsEmptyWithNoDatabases(t *testing.T) {
	m := NewGeoIPManager(t.TempDir())
	r := m.Reader()
	if !r.IsEmpty() {
		t.Error("Reader() should be empty when no databases are loaded")
	}
}

// --- loadDatabases error paths ---

func TestLoadDatabases_MissingDatabases(t *testing.T) {
	m := NewGeoIPManager(t.TempDir())
	err := m.loadDatabases()
	if err == nil {
		t.Fatal("expected error when no database files exist at all")
	}
}

// Per AI.md PART 19's fail-open mandate, loadDatabases is resilient
// per-file: one invalid/missing database must not prevent the others
// from loading successfully.
func TestLoadDatabases_InvalidFile_OthersStillLoad(t *testing.T) {
	dir := t.TempDir()
	m := NewGeoIPManager(dir)
	geoDir := filepath.Join(dir, "security", "geoip")
	if err := os.MkdirAll(geoDir, 0755); err != nil {
		t.Fatal(err)
	}
	// asn is invalid; the rest are valid minimal MMDB files.
	if err := os.WriteFile(m.asnFile, []byte("not an mmdb"), 0644); err != nil {
		t.Fatal(err)
	}
	for _, f := range []string{m.countryFile, m.cityV4File, m.cityV6File} {
		if err := os.WriteFile(f, minimalMMDB, 0644); err != nil {
			t.Fatal(err)
		}
	}
	if err := m.loadDatabases(); err != nil {
		t.Fatalf("expected loadDatabases to succeed with 3/4 valid files, got: %v", err)
	}
	if m.asnDB != nil {
		t.Error("expected asnDB to remain nil after failing to load")
	}
	if m.countryDB == nil || m.cityV4DB == nil || m.cityV6DB == nil {
		t.Error("expected country/cityV4/cityV6 readers to be loaded despite asn failure")
	}
}

func TestLoadDatabases_AllFilesInvalid_ReturnsError(t *testing.T) {
	dir := t.TempDir()
	m := NewGeoIPManager(dir)
	geoDir := filepath.Join(dir, "security", "geoip")
	if err := os.MkdirAll(geoDir, 0755); err != nil {
		t.Fatal(err)
	}
	for _, f := range allFiles(m) {
		if err := os.WriteFile(f, []byte("not an mmdb"), 0644); err != nil {
			t.Fatal(err)
		}
	}
	if err := m.loadDatabases(); err == nil {
		t.Fatal("expected error when all database files are invalid")
	}
}

func TestLoadDatabases_ValidMinimalMMDB(t *testing.T) {
	dir := t.TempDir()
	m := NewGeoIPManager(dir)
	geoDir := filepath.Join(dir, "security", "geoip")
	if err := os.MkdirAll(geoDir, 0755); err != nil {
		t.Fatal(err)
	}
	// Write valid minimal MMDB to all four files
	for _, f := range allFiles(m) {
		if err := os.WriteFile(f, minimalMMDB, 0644); err != nil {
			t.Fatal(err)
		}
	}
	if err := m.loadDatabases(); err != nil {
		t.Fatalf("unexpected error loading valid MMDB files: %v", err)
	}
	if m.asnDB == nil || m.countryDB == nil || m.cityV4DB == nil || m.cityV6DB == nil {
		t.Error("expected all DB readers to be non-nil after successful load")
	}
}

// --- Initialize ---

func TestInitialize_CreatesDirectory(t *testing.T) {
	dir := t.TempDir()
	m := NewGeoIPManager(dir)
	geoDir := filepath.Join(dir, "security", "geoip")
	// Remove it if created by parent
	os.RemoveAll(geoDir)
	// Initialize will fail at download step, but should create the directory first.
	// Pre-populate valid files so Initialize succeeds without network access.
	if err := os.MkdirAll(geoDir, 0755); err != nil {
		t.Fatal(err)
	}
	for _, f := range allFiles(m) {
		if err := os.WriteFile(f, minimalMMDB, 0644); err != nil {
			t.Fatal(err)
		}
	}
	if err := m.Initialize(); err != nil {
		t.Fatalf("Initialize failed: %v", err)
	}
	if _, err := os.Stat(geoDir); os.IsNotExist(err) {
		t.Error("expected geoip directory to exist after Initialize")
	}
	if m.lastUpdate.IsZero() {
		t.Error("expected lastUpdate to be set after Initialize")
	}
}

// Per AI.md PART 19's fail-open mandate, a corrupt asn.mmdb must not take
// down GeoIP entirely — Initialize succeeds and serves the other databases.
func TestInitialize_CorruptAsnFile_FailsOpen(t *testing.T) {
	dir := t.TempDir()
	m := NewGeoIPManager(dir)
	geoDir := filepath.Join(dir, "security", "geoip")
	if err := os.MkdirAll(geoDir, 0755); err != nil {
		t.Fatal(err)
	}
	// Write valid MMDB to all files except asn, which gets corrupt data
	for _, f := range []string{m.countryFile, m.cityV4File, m.cityV6File} {
		if err := os.WriteFile(f, minimalMMDB, 0644); err != nil {
			t.Fatal(err)
		}
	}
	if err := os.WriteFile(m.asnFile, []byte("this is not a valid mmdb file"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := m.Initialize(); err != nil {
		t.Fatalf("expected Initialize to fail open with a corrupt asn file, got: %v", err)
	}
	if m.GetStatus().ASNEnabled {
		t.Error("expected ASNEnabled false after asn file failed to load")
	}
	if !m.GetStatus().CountryEnabled {
		t.Error("expected CountryEnabled true — country file was valid")
	}
}

// --- Update ---

func TestUpdate_SkipsWhenRecentlyUpdated(t *testing.T) {
	m := NewGeoIPManager(t.TempDir())
	m.lastUpdate = time.Now()
	// Should not attempt download or load — returns nil immediately
	if err := m.Update(); err != nil {
		t.Fatalf("Update() should be no-op when recently updated: %v", err)
	}
}

// --- downloadFile ---

func TestDownloadFile_Success(t *testing.T) {
	content := []byte("fake mmdb content for test")
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
		w.Write(content)
	}))
	defer srv.Close()

	dir := t.TempDir()
	m := NewGeoIPManager(dir)
	dest := filepath.Join(dir, "test.mmdb")

	if err := m.downloadFile(srv.URL, dest); err != nil {
		t.Fatalf("downloadFile failed: %v", err)
	}
	got, err := os.ReadFile(dest)
	if err != nil {
		t.Fatalf("ReadFile failed: %v", err)
	}
	if string(got) != string(content) {
		t.Errorf("downloaded content = %q, want %q", got, content)
	}
}

func TestDownloadFile_HTTP404(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		http.NotFound(w, r)
	}))
	defer srv.Close()

	dir := t.TempDir()
	m := NewGeoIPManager(dir)
	err := m.downloadFile(srv.URL, filepath.Join(dir, "out.mmdb"))
	if err == nil {
		t.Fatal("expected error for HTTP 404")
	}
}

func TestDownloadFile_HTTP500(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		http.Error(w, "boom", http.StatusInternalServerError)
	}))
	defer srv.Close()

	dir := t.TempDir()
	m := NewGeoIPManager(dir)
	err := m.downloadFile(srv.URL, filepath.Join(dir, "out.mmdb"))
	if err == nil {
		t.Fatal("expected error for HTTP 500")
	}
}

func TestDownloadFile_ConnectionRefused(t *testing.T) {
	dir := t.TempDir()
	m := NewGeoIPManager(dir)
	// Use a port that is not listening
	err := m.downloadFile("http://127.0.0.1:0/noexist", filepath.Join(dir, "out.mmdb"))
	if err == nil {
		t.Fatal("expected error when connection is refused")
	}
}

func TestDownloadFile_UnwritableDestination(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("data"))
	}))
	defer srv.Close()

	m := NewGeoIPManager(t.TempDir())
	// Use a path inside a non-existent directory
	err := m.downloadFile(srv.URL, "/nonexistent/dir/file.mmdb")
	if err == nil {
		t.Fatal("expected error when destination directory does not exist")
	}
}

// --- DownloadDatabases (file path verification) ---

func TestDownloadDatabases_FilePathsCorrect(t *testing.T) {
	dir := t.TempDir()
	m := NewGeoIPManager(dir)
	geoDir := filepath.Join(dir, "security", "geoip")

	// Validate file paths are correctly derived from the data dir
	if m.asnFile != filepath.Join(geoDir, "asn.mmdb") {
		t.Errorf("asnFile path mismatch: %q", m.asnFile)
	}
	if m.countryFile != filepath.Join(geoDir, "country.mmdb") {
		t.Errorf("countryFile path mismatch: %q", m.countryFile)
	}
	if m.cityV4File != filepath.Join(geoDir, "dbip-city-ipv4.mmdb") {
		t.Errorf("cityV4File path mismatch: %q", m.cityV4File)
	}
	if m.cityV6File != filepath.Join(geoDir, "dbip-city-ipv6.mmdb") {
		t.Errorf("cityV6File path mismatch: %q", m.cityV6File)
	}
}

// --- ForceUpdate (error propagation) ---

func TestForceUpdate_FailsWhenNoNetwork(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping network test in short mode")
	}
	m := NewGeoIPManager(t.TempDir())
	// ForceUpdate calls DownloadDatabases which tries real CDN URLs.
	// This should fail in an offline/CI context with a network error.
	// We accept either a download error or a load error.
	err := m.ForceUpdate()
	if err == nil {
		// Acceptable only if we accidentally have network + valid CDN responses
		// (rare in test environments but possible); skip rather than fail
		t.Skip("ForceUpdate succeeded unexpectedly (network available with valid CDN)")
	}
}

// --- minimalMMDB self-check ---

func TestMinimalMMDB_ParsesCorrectly(t *testing.T) {
	r, err := maxminddb.FromBytes(minimalMMDB)
	if err != nil {
		t.Fatalf("minimalMMDB failed to parse: %v", err)
	}
	if r.Metadata.IPVersion != 4 {
		t.Errorf("IPVersion = %d, want 4", r.Metadata.IPVersion)
	}
	if r.Metadata.NodeCount != 1 {
		t.Errorf("NodeCount = %d, want 1", r.Metadata.NodeCount)
	}
	if r.Metadata.RecordSize != 24 {
		t.Errorf("RecordSize = %d, want 24", r.Metadata.RecordSize)
	}
}

func TestMinimalMMDB_LookupReturnsEmpty(t *testing.T) {
	r, err := maxminddb.FromBytes(minimalMMDB)
	if err != nil {
		t.Fatalf("minimalMMDB failed to parse: %v", err)
	}
	var result map[string]interface{}
	if err := r.Lookup(net.ParseIP("8.8.8.8"), &result); err != nil {
		t.Fatalf("Lookup failed: %v", err)
	}
	if len(result) != 0 {
		t.Errorf("expected empty result, got %v", result)
	}
}
